apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bridge-metrics
  labels:
    app: strimzi
    prometheus: main
spec:
  selector:
    matchLabels:
      strimzi.io/kind: KafkaBridge
  namespaceSelector:
    matchNames:
      - data-mesh
      - strimzi-kafka
  podMetricsEndpoints:
  - path: /metrics
    port: rest-api