apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: entity-operator-metrics
  labels:
    app: strimzi
    prometheus: main
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - data-mesh
      - strimzi-kafka
  podMetricsEndpoints:
  - path: /metrics
    port: healthcheck
