apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: backend
          # used with docker io repository
          # image: docker.io/datawire/quote:0.4.1
          # used with local repository
          image: k3d-dev-repo.localhost/datawire/quote:0.4.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quote-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: quote
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-ingress
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  #   kubernetes.io/ingress.class: nginx
  #   # nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - quote.brimdataservices.com.br
      secretName: ingress-quote-certificate
  rules:
    - host: quote.brimdataservices.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quote-svc
                port:
                  number: 80