apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
 name: movies
 labels:
   strimzi.io/cluster: data-mesh
spec:
 partitions: 3
 replicas: 2
 config:
   retention.ms: 7200000
   segment.bytes: 1073741824