apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
 name: movies
 labels:
   strimzi.io/cluster: data-mesh
spec:
 partitions: 3
 replicas: 1
 config:
   retention.ms: 300000
   segment.bytes: 1000000000