apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb-server
  labels:
    app: ksqldb-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ksqldb-server
  template:
    metadata:
      labels:
        app: ksqldb-server
    spec:
      containers:
      - name: ksqldb-server
        image: confluentinc/ksqldb-server:0.12.0
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-cluster-kafka-bootstrap.data-mesh.svc.cluster.local:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
          value: "1"
        - name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
          value: "1"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
          value: "1"
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 2000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb-server
spec:
  selector:
    app: ksqldb-server
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb-headless
  # namespace: processing
spec:
  clusterIP: None
  selector:
    app: ksqldb-server
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088